server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  security:
    user:
      name: user
      password: password

  datasource:
    password: Daniel@123
    url: jdbc:postgresql://localhost:5432/observer_registration
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

